/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ControllerPesquisar;
import dao.DAOgeneric;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 *
 * @author bispo
 */
public class JDlgPesquisar extends javax.swing.JDialog {

    /**
     * Creates new form JDlgUsuarioPesquisar
     */
    ControllerPesquisar controllerPesquisar;
    String tela = "Usuarios";
    JDialog telaA;
    Class clazz;
    Object objeto;
    Class clazzTela;
    Method bv;

    public JDlgPesquisar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDlgPesquisar(java.awt.Frame parent, boolean modal, Class<?> c, Object o, Class ct, JDialog t, String nt) {
        super(parent, modal);
        initComponents();
        setTitle("Pesquisa " + getTela());
        setLocationRelativeTo(null);
        setBean(c); //classe bean
        setObject(o); //objeto
        setTelaAnterior(t); //tela 
        setClazzTela(ct); //classe da tela
        setTela(nt);

        controllerPesquisar = new ControllerPesquisar(getBean());

        DAOgeneric dao = new DAOgeneric();
        List lista = dao.listAll(getBean());

        controllerPesquisar.setList(lista);
        ebs_jTblPesquisa.setModel(controllerPesquisar);
    }

    public final String getTela() {
        return tela;
    }

    public final void setTela(String tela) {
        this.tela = tela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ebs_jTblPesquisa = new javax.swing.JTable();
        jBtnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ebs_jTblPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ebs_jTblPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ebs_jTblPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ebs_jTblPesquisa);

        jBtnOK.setText("OK");
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOKActionPerformed
        objeto = controllerPesquisar.getBean(ebs_jTblPesquisa.getSelectedRow());

        Method[] listMethods = getClazzTela().getDeclaredMethods();
        for (Method method : listMethods) {
            if (method.getName().equals("beanview")) {
                bv = method;
                //System.out.println("bv:  "+bv);
            }
        }
        bv.setAccessible(true);
        try {
            bv.invoke(getTelaAnterior(), objeto);
        } catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(JDlgPesquisar.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jBtnOKActionPerformed

    private void ebs_jTblPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ebs_jTblPesquisaMouseClicked

    }//GEN-LAST:event_ebs_jTblPesquisaMouseClicked

    private void setTelaAnterior(JDialog telaAnterior) {
        this.telaA = telaAnterior;
    }

    public JDialog getTelaAnterior() {
        return this.telaA;
    }

    public Class getClazzTela() {
        return this.clazzTela;
    }

    private void setClazzTela(Class ct) {
        this.clazzTela = ct;
    }

    private void setBean(Class clazz) {
        this.clazz = clazz;
    }

    private Class getBean() {
        return this.clazz;
    }

    private void setObject(Object object) {
        this.objeto = object;
    }

    public Object getObject() {
        return this.objeto;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JDlgPesquisar dialog = new JDlgPesquisar(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ebs_jTblPesquisa;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
