/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.EbsCompraProduto;
import bean.EbsCompraProdutoId;
import bean.EbsProduto;
import dao.DAOgeneric;
import java.util.List;
import tools.Util;

/**
 *
 * @author bispo
 */
public class JDlgCompraProduto extends javax.swing.JDialog {

    /**
     * Creates new form JDlgEbsCompraProduto
     */
    int compraID;
    JDlgCompra jDlgCompra;

    public JDlgCompraProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Compra Produto");
        setLocationRelativeTo(null);

    }
    
    public JDlgCompraProduto(java.awt.Frame parent, boolean modal, JDlgCompra telaAnterior, int compraIDa) {
        super(parent, modal);
        initComponents();
        setTitle("Compra Produto");
        setLocationRelativeTo(null);
        
        this.jDlgCompra = telaAnterior;
        this.compraID = compraIDa;
        ebs_jTxtIdCompra.setText(Util.intToStr(compraID));
        
        Util.habilitar(false, ebs_jTxtValorUnitario, ebs_jTxtTotal, ebs_jTxtIdCompra);
        
        dao.DAOgeneric dao = new DAOgeneric();

        List listProdutos = dao.listAll(EbsProduto.class);
        for (Object p : listProdutos) {
            ebs_jCboProduto.addItem((EbsProduto) p);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblProduto = new javax.swing.JLabel();
        ebs_jCboProduto = new javax.swing.JComboBox<EbsProduto>();
        jLblQuantidade = new javax.swing.JLabel();
        ebs_jTxtQuantidade = new javax.swing.JTextField();
        jLblValorUnitario = new javax.swing.JLabel();
        ebs_jTxtValorUnitario = new javax.swing.JTextField();
        jLblTotal = new javax.swing.JLabel();
        ebs_jTxtTotal = new javax.swing.JTextField();
        ebs_jBtnCancelar = new javax.swing.JButton();
        ebs_jBtnOk = new javax.swing.JButton();
        jLblCompra = new javax.swing.JLabel();
        ebs_jTxtIdCompra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblProduto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLblProduto.setText("Produto");

        ebs_jCboProduto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ebs_jCboProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebs_jCboProdutoActionPerformed(evt);
            }
        });

        jLblQuantidade.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLblQuantidade.setText("Quantidade");

        ebs_jTxtQuantidade.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ebs_jTxtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ebs_jTxtQuantidadeKeyReleased(evt);
            }
        });

        jLblValorUnitario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLblValorUnitario.setText("Valor Unitário");

        ebs_jTxtValorUnitario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jLblTotal.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLblTotal.setText("Total");

        ebs_jTxtTotal.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        ebs_jBtnCancelar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ebs_jBtnCancelar.setText("Cancelar");
        ebs_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebs_jBtnCancelarActionPerformed(evt);
            }
        });

        ebs_jBtnOk.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ebs_jBtnOk.setText("OK");
        ebs_jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebs_jBtnOkActionPerformed(evt);
            }
        });

        jLblCompra.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLblCompra.setText("Compra");

        ebs_jTxtIdCompra.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        ebs_jTxtIdCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ebs_jTxtIdCompraKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ebs_jBtnOk)
                            .addGap(18, 18, 18)
                            .addComponent(ebs_jBtnCancelar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblQuantidade)
                                .addComponent(ebs_jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLblValorUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ebs_jTxtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblTotal)
                                .addComponent(ebs_jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCompra)
                            .addComponent(ebs_jTxtIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblProduto)
                            .addComponent(ebs_jCboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCompra)
                    .addComponent(jLblProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ebs_jCboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ebs_jTxtIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ebs_jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblValorUnitario)
                            .addComponent(jLblTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ebs_jTxtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ebs_jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ebs_jBtnCancelar)
                    .addComponent(ebs_jBtnOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private EbsCompraProduto viewbean() {
        EbsCompraProduto compraProduto = new EbsCompraProduto();
        
        EbsProduto produto = (EbsProduto) ebs_jCboProduto.getSelectedItem();
        EbsCompraProdutoId compraProdutoID = new EbsCompraProdutoId();
        compraProdutoID.setEbsFkCompra(compraID);
        compraProdutoID.setEbsFkProduto(produto.getEbsIdProduto());
        
        compraProduto.setId(compraProdutoID);
        compraProduto.setEbsProduto(produto);
        compraProduto.setEbsQuantidade(Util.strToInt(ebs_jTxtQuantidade.getText()));
        compraProduto.setEbsValorUnit(Util.strToDouble(ebs_jTxtValorUnitario.getText()));

        return compraProduto;
    }

    public void beanview(EbsCompraProduto compraProduto) {
        ebs_jCboProduto.setSelectedItem(compraProduto.getEbsProduto());
        ebs_jTxtQuantidade.setText(Util.intToStr(compraProduto.getEbsQuantidade()));
        ebs_jTxtValorUnitario.setText(Util.doubleToStr(compraProduto.getEbsValorUnit()));
    }

    private void ebs_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebs_jBtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_ebs_jBtnCancelarActionPerformed

    private void ebs_jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebs_jBtnOkActionPerformed
        if (viewbean().getEbsQuantidade() == 0) {
            Util.mostrar("Quantidade não pode ser 0", "Aviso");
            ebs_jTxtQuantidade.grabFocus();
        } else {
            jDlgCompra.controllerCompraProdutos.addBean(viewbean());
            this.dispose();
        }
    }//GEN-LAST:event_ebs_jBtnOkActionPerformed

    private void ebs_jCboProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebs_jCboProdutoActionPerformed
        EbsProduto p = (EbsProduto) ebs_jCboProduto.getSelectedItem();
        ebs_jTxtValorUnitario.setText(Util.doubleToStr(p.getEbsValor()));
        ebs_jTxtTotal.setText(Util.doubleToStr(p.getEbsValor()));
        ebs_jTxtQuantidade.setText("1");
    }//GEN-LAST:event_ebs_jCboProdutoActionPerformed

    private void ebs_jTxtQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ebs_jTxtQuantidadeKeyReleased
        if (ebs_jTxtQuantidade.getText().equals("")) {
            ebs_jTxtTotal.setText("0");
        } else {
            int qtd = Util.strToInt(ebs_jTxtQuantidade.getText());
            double unitario = Util.strToDouble(ebs_jTxtValorUnitario.getText());
            double total = qtd * unitario;
            ebs_jTxtTotal.setText(Util.doubleToStr(total));
        }
    }//GEN-LAST:event_ebs_jTxtQuantidadeKeyReleased

    private void ebs_jTxtIdCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ebs_jTxtIdCompraKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ebs_jTxtIdCompraKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCompraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCompraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCompraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCompraProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JDlgCompraProduto dialog = new JDlgCompraProduto(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ebs_jBtnCancelar;
    private javax.swing.JButton ebs_jBtnOk;
    private javax.swing.JComboBox<EbsProduto> ebs_jCboProduto;
    private javax.swing.JTextField ebs_jTxtIdCompra;
    private javax.swing.JTextField ebs_jTxtQuantidade;
    private javax.swing.JTextField ebs_jTxtTotal;
    private javax.swing.JTextField ebs_jTxtValorUnitario;
    private javax.swing.JLabel jLblCompra;
    private javax.swing.JLabel jLblProduto;
    private javax.swing.JLabel jLblQuantidade;
    private javax.swing.JLabel jLblTotal;
    private javax.swing.JLabel jLblValorUnitario;
    // End of variables declaration//GEN-END:variables
}
