package bean;
// Generated 08/12/2024 10:31:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EbsCompraProdutoId generated by hbm2java
 */
@Embeddable
public class EbsCompraProdutoId  implements java.io.Serializable {


     private int ebsFkProduto;
     private int ebsFkCompra;

    public EbsCompraProdutoId() {
    }

    public EbsCompraProdutoId(int ebsFkProduto, int ebsFkCompra) {
       this.ebsFkProduto = ebsFkProduto;
       this.ebsFkCompra = ebsFkCompra;
    }
   


    @Column(name="ebs_fk_produto", nullable=false)
    public int getEbsFkProduto() {
        return this.ebsFkProduto;
    }
    
    public void setEbsFkProduto(int ebsFkProduto) {
        this.ebsFkProduto = ebsFkProduto;
    }


    @Column(name="ebs_fk_compra", nullable=false)
    public int getEbsFkCompra() {
        return this.ebsFkCompra;
    }
    
    public void setEbsFkCompra(int ebsFkCompra) {
        this.ebsFkCompra = ebsFkCompra;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EbsCompraProdutoId) ) return false;
		 EbsCompraProdutoId castOther = ( EbsCompraProdutoId ) other; 
         
		 return (this.getEbsFkProduto()==castOther.getEbsFkProduto())
 && (this.getEbsFkCompra()==castOther.getEbsFkCompra());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEbsFkProduto();
         result = 37 * result + this.getEbsFkCompra();
         return result;
   }   


}


