package bean;
// Generated 08/12/2024 10:31:19 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EbsCategoria generated by hbm2java
 */
@Entity
@Table(name = "ebs_categoria", catalog = "db_emanuel_silva"
)
public class EbsCategoria implements java.io.Serializable {

    private int ebsIdCategoria;
    private String ebsNome;

    public EbsCategoria() {
    }

    public EbsCategoria(int ebsIdCategoria, String ebsNome) {
        this.ebsIdCategoria = ebsIdCategoria;
        this.ebsNome = ebsNome;
    }

    @Id

    @Column(name = "ebs_id_categoria", unique = true, nullable = false)
    public int getEbsIdCategoria() {
        return this.ebsIdCategoria;
    }

    public void setEbsIdCategoria(int ebsIdCategoria) {
        this.ebsIdCategoria = ebsIdCategoria;
    }

    @Column(name = "ebs_nome", nullable = false, length = 50)
    public String getEbsNome() {
        return this.ebsNome;
    }

    public void setEbsNome(String ebsNome) {
        this.ebsNome = ebsNome;
    }

    @Override
    public String toString() {
        return this.getEbsNome();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof EbsCategoria) {
            EbsCategoria c = (EbsCategoria) obj;
            if (c.getEbsIdCategoria()== this.getEbsIdCategoria()) {
                return true;
            }
        }
        return false;
    }
}
