package bean;
// Generated 08/12/2024 10:31:19 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import tools.Util;

/**
 * EbsCompra generated by hbm2java
 */
@Entity
@Table(name="ebs_compra"
    ,catalog="db_emanuel_silva"
)
public class EbsCompra  implements java.io.Serializable {


     private int ebsIdCompra;
     private EbsFornecedor ebsFornecedor;
     private EbsUsuario ebsUsuario;
     private Date ebsDataCompra;
     private double ebsTotal;

    public EbsCompra() {
    }

	
    public EbsCompra(int ebsIdCompra, EbsFornecedor ebsFornecedor, EbsUsuario ebsUsuario, Date ebsDataCompra, double ebsTotal) {
        this.ebsIdCompra = ebsIdCompra;
        this.ebsFornecedor = ebsFornecedor;
        this.ebsUsuario = ebsUsuario;
        this.ebsDataCompra = ebsDataCompra;
        this.ebsTotal = ebsTotal;
    }
   
     @Id 

    
    @Column(name="ebs_id_compra", unique=true, nullable=false)
    public int getEbsIdCompra() {
        return this.ebsIdCompra;
    }
    
    public void setEbsIdCompra(int ebsIdCompra) {
        this.ebsIdCompra = ebsIdCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ebs_fk_fornecedor", nullable=false)
    public EbsFornecedor getEbsFornecedor() {
        return this.ebsFornecedor;
    }
    
    public void setEbsFornecedor(EbsFornecedor ebsFornecedor) {
        this.ebsFornecedor = ebsFornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ebs_fk_usuario", nullable=false)
    public EbsUsuario getEbsUsuario() {
        return this.ebsUsuario;
    }
    
    public void setEbsUsuario(EbsUsuario ebsUsuario) {
        this.ebsUsuario = ebsUsuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ebs_data_compra", nullable=false, length=10)
    public Date getEbsDataCompra() {
        return this.ebsDataCompra;
    }
    
    public void setEbsDataCompra(Date ebsDataCompra) {
        this.ebsDataCompra = ebsDataCompra;
    }

    
    @Column(name="ebs_total", nullable=false, precision=10)
    public double getEbsTotal() {
        return this.ebsTotal;
    }
    
    public void setEbsTotal(double ebsTotal) {
        this.ebsTotal = ebsTotal;
    }

    @Override
    public String toString() {
        return Util.intToStr(this.getEbsIdCompra());
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof EbsCompra) {
            EbsCompra c = (EbsCompra) obj;
            if (c.getEbsIdCompra()== this.getEbsIdCompra()) {
                return true;
            }
        }
        return false;
    }
    
}


