package bean;
// Generated 08/12/2024 10:31:19 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EbsFornecedor generated by hbm2java
 */
@Entity
@Table(name = "ebs_fornecedor", catalog = "db_emanuel_silva"
)
public class EbsFornecedor implements java.io.Serializable {

    private int ebsIdFornecedor;
    private EbsTransportadora ebsTransportadora;
    private String ebsAtivo;
    private String ebsNomeFornecedor;
    private String ebsCelular;
    private String ebsNomeEmpresa;
    private String ebsTelefone;
    private String ebsNomeFant;
    private String ebsCnpj;
    private String ebsSiteEmpresa;
    private String ebsEmail;
    private String ebsEndereco;
    private String ebsNumero;
    private String ebsBairro;
    private String ebsCidade;
    private String ebsEstado;

    public EbsFornecedor() {
    }

    public EbsFornecedor(int ebsIdFornecedor, EbsTransportadora ebsTransportadora, String ebsAtivo, String ebsNomeFornecedor, String ebsCelular, String ebsNomeEmpresa, String ebsTelefone, String ebsNomeFant, String ebsCnpj, String ebsSiteEmpresa, String ebsEmail, String ebsEndereco, String ebsNumero, String ebsBairro, String ebsCidade, String ebsEstado) {
        this.ebsIdFornecedor = ebsIdFornecedor;
        this.ebsTransportadora = ebsTransportadora;
        this.ebsAtivo = ebsAtivo;
        this.ebsNomeFornecedor = ebsNomeFornecedor;
        this.ebsCelular = ebsCelular;
        this.ebsNomeEmpresa = ebsNomeEmpresa;
        this.ebsTelefone = ebsTelefone;
        this.ebsNomeFant = ebsNomeFant;
        this.ebsCnpj = ebsCnpj;
        this.ebsSiteEmpresa = ebsSiteEmpresa;
        this.ebsEmail = ebsEmail;
        this.ebsEndereco = ebsEndereco;
        this.ebsNumero = ebsNumero;
        this.ebsBairro = ebsBairro;
        this.ebsCidade = ebsCidade;
        this.ebsEstado = ebsEstado;
    }

    @Id

    @Column(name = "ebs_id_fornecedor", unique = true, nullable = false)
    public int getEbsIdFornecedor() {
        return this.ebsIdFornecedor;
    }

    public void setEbsIdFornecedor(int ebsIdFornecedor) {
        this.ebsIdFornecedor = ebsIdFornecedor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ebs_fk_transportadora", nullable = false)
    public EbsTransportadora getEbsTransportadora() {
        return this.ebsTransportadora;
    }

    public void setEbsTransportadora(EbsTransportadora ebsTransportadora) {
        this.ebsTransportadora = ebsTransportadora;
    }

    @Column(name = "ebs_ativo", nullable = false, length = 1)
    public String getEbsAtivo() {
        return this.ebsAtivo;
    }

    public void setEbsAtivo(String ebsAtivo) {
        this.ebsAtivo = ebsAtivo;
    }

    @Column(name = "ebs_nome_fornecedor", nullable = false, length = 50)
    public String getEbsNomeFornecedor() {
        return this.ebsNomeFornecedor;
    }

    public void setEbsNomeFornecedor(String ebsNomeFornecedor) {
        this.ebsNomeFornecedor = ebsNomeFornecedor;
    }

    @Column(name = "ebs_celular", nullable = false, length = 14)
    public String getEbsCelular() {
        return this.ebsCelular;
    }

    public void setEbsCelular(String ebsCelular) {
        this.ebsCelular = ebsCelular;
    }

    @Column(name = "ebs_nome_empresa", nullable = false, length = 50)
    public String getEbsNomeEmpresa() {
        return this.ebsNomeEmpresa;
    }

    public void setEbsNomeEmpresa(String ebsNomeEmpresa) {
        this.ebsNomeEmpresa = ebsNomeEmpresa;
    }

    @Column(name = "ebs_telefone", nullable = false, length = 14)
    public String getEbsTelefone() {
        return this.ebsTelefone;
    }

    public void setEbsTelefone(String ebsTelefone) {
        this.ebsTelefone = ebsTelefone;
    }

    @Column(name = "ebs_nome_fant", nullable = false, length = 50)
    public String getEbsNomeFant() {
        return this.ebsNomeFant;
    }

    public void setEbsNomeFant(String ebsNomeFant) {
        this.ebsNomeFant = ebsNomeFant;
    }

    @Column(name = "ebs_cnpj", nullable = false, length = 18)
    public String getEbsCnpj() {
        return this.ebsCnpj;
    }

    public void setEbsCnpj(String ebsCnpj) {
        this.ebsCnpj = ebsCnpj;
    }

    @Column(name = "ebs_site_empresa", nullable = false, length = 50)
    public String getEbsSiteEmpresa() {
        return this.ebsSiteEmpresa;
    }

    public void setEbsSiteEmpresa(String ebsSiteEmpresa) {
        this.ebsSiteEmpresa = ebsSiteEmpresa;
    }

    @Column(name = "ebs_email", nullable = false, length = 60)
    public String getEbsEmail() {
        return this.ebsEmail;
    }

    public void setEbsEmail(String ebsEmail) {
        this.ebsEmail = ebsEmail;
    }

    @Column(name = "ebs_endereco", nullable = false, length = 100)
    public String getEbsEndereco() {
        return this.ebsEndereco;
    }

    public void setEbsEndereco(String ebsEndereco) {
        this.ebsEndereco = ebsEndereco;
    }

    @Column(name = "ebs_numero", nullable = false, length = 4)
    public String getEbsNumero() {
        return this.ebsNumero;
    }

    public void setEbsNumero(String ebsNumero) {
        this.ebsNumero = ebsNumero;
    }

    @Column(name = "ebs_bairro", nullable = false, length = 30)
    public String getEbsBairro() {
        return this.ebsBairro;
    }

    public void setEbsBairro(String ebsBairro) {
        this.ebsBairro = ebsBairro;
    }

    @Column(name = "ebs_cidade", nullable = false, length = 30)
    public String getEbsCidade() {
        return this.ebsCidade;
    }

    public void setEbsCidade(String ebsCidade) {
        this.ebsCidade = ebsCidade;
    }

    @Column(name = "ebs_estado", nullable = false, length = 2)
    public String getEbsEstado() {
        return this.ebsEstado;
    }

    public void setEbsEstado(String ebsEstado) {
        this.ebsEstado = ebsEstado;
    }

    @Override
    public String toString() {
        return this.getEbsNomeFornecedor();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof EbsFornecedor) {
            EbsFornecedor f = (EbsFornecedor) obj;
            if (f.getEbsIdFornecedor()== this.getEbsIdFornecedor()) {
                return true;
            }
        }
        return false;
    }

}
