package bean;
// Generated 08/12/2024 10:31:19 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EbsProduto generated by hbm2java
 */
@Entity
@Table(name = "ebs_produto", catalog = "db_emanuel_silva"
)
public class EbsProduto implements java.io.Serializable {

    private int ebsIdProduto;
    private EbsCategoria ebsCategoria;
    private String ebsNome;
    private double ebsValor;
    private Date ebsDataChegada;
    private Date ebsDataValidade;
    private int ebsEstoque;

    public EbsProduto() {
    }

    public EbsProduto(int ebsIdProduto, EbsCategoria ebsCategoria, String ebsNome, double ebsValor, Date ebsDataChegada, Date ebsDataValidade, int ebsEstoque) {
        this.ebsIdProduto = ebsIdProduto;
        this.ebsCategoria = ebsCategoria;
        this.ebsNome = ebsNome;
        this.ebsValor = ebsValor;
        this.ebsDataChegada = ebsDataChegada;
        this.ebsDataValidade = ebsDataValidade;
        this.ebsEstoque = ebsEstoque;
    }

    @Id

    @Column(name = "ebs_id_produto", unique = true, nullable = false)
    public int getEbsIdProduto() {
        return this.ebsIdProduto;
    }

    public void setEbsIdProduto(int ebsIdProduto) {
        this.ebsIdProduto = ebsIdProduto;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ebs_fk_categoria", nullable = false)
    public EbsCategoria getEbsCategoria() {
        return this.ebsCategoria;
    }

    public void setEbsCategoria(EbsCategoria ebsCategoria) {
        this.ebsCategoria = ebsCategoria;
    }

    @Column(name = "ebs_nome", nullable = false, length = 50)
    public String getEbsNome() {
        return this.ebsNome;
    }

    public void setEbsNome(String ebsNome) {
        this.ebsNome = ebsNome;
    }

    @Column(name = "ebs_valor", nullable = false, precision = 10)
    public double getEbsValor() {
        return this.ebsValor;
    }

    public void setEbsValor(double ebsValor) {
        this.ebsValor = ebsValor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ebs_data_chegada", nullable = false, length = 10)
    public Date getEbsDataChegada() {
        return this.ebsDataChegada;
    }

    public void setEbsDataChegada(Date ebsDataChegada) {
        this.ebsDataChegada = ebsDataChegada;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ebs_data_validade", nullable = false, length = 10)
    public Date getEbsDataValidade() {
        return this.ebsDataValidade;
    }

    public void setEbsDataValidade(Date ebsDataValidade) {
        this.ebsDataValidade = ebsDataValidade;
    }

    @Column(name = "ebs_estoque", nullable = false)
    public int getEbsEstoque() {
        return this.ebsEstoque;
    }

    public void setEbsEstoque(int ebsEstoque) {
        this.ebsEstoque = ebsEstoque;
    }

    @Override
    public String toString() {
        return this.getEbsNome();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof EbsProduto) {
            EbsProduto p = (EbsProduto) obj;
            if (p.getEbsIdProduto() == this.getEbsIdProduto()) {
                return true;
            }
        }
        return false;
    }

}
