package bean;
// Generated 08/12/2024 10:31:19 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EbsTransportadora generated by hbm2java
 */
@Entity
@Table(name = "ebs_transportadora", catalog = "db_emanuel_silva"
)
public class EbsTransportadora implements java.io.Serializable {

    private int ebsIdTransportadora;
    private String ebsCnpj;
    private String ebsNome;
    private String ebsResponsavel;
    private String ebsEmail;
    private String ebsTelefone;
    private String ebsEndereco;

    public EbsTransportadora() {
    }

    public EbsTransportadora(int ebsIdTransportadora, String ebsCnpj, String ebsNome, String ebsResponsavel, String ebsEmail, String ebsTelefone, String ebsEndereco) {
        this.ebsIdTransportadora = ebsIdTransportadora;
        this.ebsCnpj = ebsCnpj;
        this.ebsNome = ebsNome;
        this.ebsResponsavel = ebsResponsavel;
        this.ebsEmail = ebsEmail;
        this.ebsTelefone = ebsTelefone;
        this.ebsEndereco = ebsEndereco;
    }

    @Id

    @Column(name = "ebs_id_transportadora", unique = true, nullable = false)
    public int getEbsIdTransportadora() {
        return this.ebsIdTransportadora;
    }

    public void setEbsIdTransportadora(int ebsIdTransportadora) {
        this.ebsIdTransportadora = ebsIdTransportadora;
    }

    @Column(name = "ebs_cnpj", nullable = false, length = 18)
    public String getEbsCnpj() {
        return this.ebsCnpj;
    }

    public void setEbsCnpj(String ebsCnpj) {
        this.ebsCnpj = ebsCnpj;
    }

    @Column(name = "ebs_nome", nullable = false, length = 50)
    public String getEbsNome() {
        return this.ebsNome;
    }

    public void setEbsNome(String ebsNome) {
        this.ebsNome = ebsNome;
    }

    @Column(name = "ebs_responsavel", nullable = false, length = 50)
    public String getEbsResponsavel() {
        return this.ebsResponsavel;
    }

    public void setEbsResponsavel(String ebsResponsavel) {
        this.ebsResponsavel = ebsResponsavel;
    }

    @Column(name = "ebs_email", nullable = false, length = 60)
    public String getEbsEmail() {
        return this.ebsEmail;
    }

    public void setEbsEmail(String ebsEmail) {
        this.ebsEmail = ebsEmail;
    }

    @Column(name = "ebs_telefone", nullable = false, length = 14)
    public String getEbsTelefone() {
        return this.ebsTelefone;
    }

    public void setEbsTelefone(String ebsTelefone) {
        this.ebsTelefone = ebsTelefone;
    }

    @Column(name = "ebs_endereco", nullable = false, length = 100)
    public String getEbsEndereco() {
        return this.ebsEndereco;
    }

    public void setEbsEndereco(String ebsEndereco) {
        this.ebsEndereco = ebsEndereco;
    }

    @Override
    public String toString() {
        return this.getEbsNome();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof EbsTransportadora) {
            EbsTransportadora t = (EbsTransportadora) obj;
            if (t.getEbsIdTransportadora() == this.getEbsIdTransportadora()) {
                return true;
            }
        }
        return false;
    }

}
