package bean;
// Generated 08/12/2024 10:31:19 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EbsUsuario generated by hbm2java
 */
@Entity
@Table(name = "ebs_usuario", catalog = "db_emanuel_silva"
)
public class EbsUsuario implements java.io.Serializable {

    private int ebsIdUsuario;
    private String ebsNome;
    private String ebsApelido;
    private String ebsCpf;
    private Date ebsDataNasc;
    private String ebsSenha;
    private int ebsNivel;
    private String ebsAtivo;

    public EbsUsuario() {
    }

    public EbsUsuario(int ebsIdUsuario, String ebsNome, String ebsApelido, String ebsCpf, Date ebsDataNasc, String ebsSenha, String ebsAtivo) {
        this.ebsIdUsuario = ebsIdUsuario;
        this.ebsNome = ebsNome;
        this.ebsApelido = ebsApelido;
        this.ebsCpf = ebsCpf;
        this.ebsDataNasc = ebsDataNasc;
        this.ebsSenha = ebsSenha;
        this.ebsAtivo = ebsAtivo;
    }

    @Id

    @Column(name = "ebs_id_usuario", unique = true, nullable = false)
    public int getEbsIdUsuario() {
        return this.ebsIdUsuario;
    }

    public void setEbsIdUsuario(int ebsIdUsuario) {
        this.ebsIdUsuario = ebsIdUsuario;
    }

    @Column(name = "ebs_nome", nullable = false, length = 50)
    public String getEbsNome() {
        return this.ebsNome;
    }

    public void setEbsNome(String ebsNome) {
        this.ebsNome = ebsNome;
    }

    @Column(name = "ebs_apelido", nullable = false, length = 50)
    public String getEbsApelido() {
        return this.ebsApelido;
    }

    public void setEbsApelido(String ebsApelido) {
        this.ebsApelido = ebsApelido;
    }

    @Column(name = "ebs_cpf", nullable = false, length = 14)
    public String getEbsCpf() {
        return this.ebsCpf;
    }

    public void setEbsCpf(String ebsCpf) {
        this.ebsCpf = ebsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ebs_data_nasc", nullable = false, length = 10)
    public Date getEbsDataNasc() {
        return this.ebsDataNasc;
    }

    public void setEbsDataNasc(Date ebsDataNasc) {
        this.ebsDataNasc = ebsDataNasc;
    }

    @Column(name = "ebs_senha", nullable = false, length = 20)
    public String getEbsSenha() {
        return this.ebsSenha;
    }

    public void setEbsSenha(String ebsSenha) {
        this.ebsSenha = ebsSenha;
    }

    @Column(name = "ebs_nivel")
    public int getEbsNivel() {
        return this.ebsNivel;
    }

    public void setEbsNivel(int ebsNivel) {
        this.ebsNivel = ebsNivel;
    }

    @Column(name = "ebs_ativo", nullable = false, length = 1)
    public String getEbsAtivo() {
        return this.ebsAtivo;
    }

    public void setEbsAtivo(String ebsAtivo) {
        this.ebsAtivo = ebsAtivo;
    }

    @Override
    public String toString() {
        return this.getEbsNome();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof EbsUsuario) {
            EbsUsuario u = (EbsUsuario) obj;
            if (u.getEbsIdUsuario()== this.getEbsIdUsuario()) {
                return true;
            }
        }
        return false;
    }
}
